version: '3.8'
services:
  books-managment:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
