version: '3.8'
services:
  books-managment-1:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./db1;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  books-managment-2:
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:./db2;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
